#!/bin/sh
#
# Perform necessary nginx-uwsgi setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1; then
    echo "Yum-based distribution detected"
    cp -f /opt/nginx-uwsgi/embedded/defaults/initscripts/init_el /etc/init.d/supervisor
    chkconfig supervisor on
else
    echo "Debian-based distribution detected"
    cp -f /opt/nginx-uwsgi/embedded/defaults/initscripts/init_debian /etc/init.d/supervisor
    update-rc.d supervisor enable
fi

exit 0
