#!/bin/sh
#
# Perform necessary nginx-uwsgi setup steps
# prior to installing package.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

rm /etc/init.d/supervisor

exit 0
